spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: 0.2
              memory: 256Mi
            limits:
              cpu: 1.0
              memory: 256Mi
          env:
          - name: BROKER_URI
            value: amqp://broker-amq-amqp:5672
          - name: BROKER_USERNAME
            value: admin
          - name: BROKER_PASSWORD
            value: admin
