# persistent volume claim for the transaction log
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boot-xa-trans
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
